[tools]
go = "1.25"
uv = "latest"
bun = "latest"

[env]
'_'.file = ".env"


[tasks.local]
run = """
hugo server -D --bind "0.0.0.0" --port 1313 -d /tmp/mika
"""

[tasks.deploy]
run = """
hugo -d /tmp/mika
cp -R /tmp/mika/* /home/haru/Projects/project-github/harus-server/harus-blog/www-data
rm -rf /tmp/mika
rm -rf resources
"""
